### ISSUE TITLE
Geen (juiste) verwerking van MultiSurface?

### ISSUE THREAD

**Issue by HermanAssink** [MarcoDuiker/QGIS_BGT_Import#10]
Marco, in o.a. bgt_overigbouwwerk.gml en bgt_pand.gml komen geometrieën van het type MultiSurface voor. Deze worden door de BGT Import plugin als Polygon in de Geopackage geladen. Bij Geoprocessing-operaties worden deze geometrieën als invalid aangemerkt. Is dit een bug in de plugin of doe ik iets fout?

**Comment by MarcoDuiker** [comment]
Kun jij mij voorzien van een gml en een object id van een object waar het misgaat?

**Comment by HermanAssink** [comment]
In bijgevoegde gml vind je MultiSurface geometrieën. Deze gml is gedownload met de beta-versie van de nieuwe BGT downloadfunctie (https://download.pdok.io/lv/bgt/viewer/)
[bgt_overigbouwwerk.zip](https://github.com/MarcoDuiker/QGIS_BGT_Import/files/3599429/bgt_overigbouwwerk.zip)

**Comment by HermanAssink** [comment]
Geometrievalidatie in QGIS geeft de foutmelding "Gat ligt buiten schil", bijv bij gml-id=baf17d3a7-1bdb-444b-852e-6940c79a49d5

**Comment by MarcoDuiker** [comment]
Inderdaad. Zorgwekkend genoeg laat ogr (die de feitelijke import verzorgt) hier een steekje vallen.
De MultiSurface wordt ingelezen als een polygoon met gat. Hoe vaak zou dit ook in andere omstandigheden misgaan?

De oplossing zit in het forceren naar de Multi-vorm van een geometrie. Dan leest ogr het wel goed in.
Ik zal dit in de plugin verwerken.

**Comment by MarcoDuiker** [comment]
hmm, het blijkt dat ogr het wel netjes doet. 
De plugin code behoefde een kleine aanpassing omdat deze de geometrie naar het single type forceerde.

**Comment by HermanAssink** [comment]
Dankjewel. Dit is een handige plugin waarmee je met "één druk op de knop" een BGT download kunt importeren in een Geopackage en met stijl en al geladen krijgt in QGIS.

**Comment by MarcoDuiker** [comment]
Inmiddels heb ik een nieuwe plugin in deze repo gezet (tag 3.12).
Kun jij deze uittesten voordat ik hem aanbied voor de QGIS repo.

**Comment by MarcoDuiker** [comment]
Fixed in versie 3.13. Inmiddels ingediend bij de QGIS repo.
Deze zal daar vanzelf verschijnen.
