### ISSUE TITLE
Diakrieten in OpenbareRuimteLabels

### ISSUE THREAD

**Issue by HansvanderMeij** [MarcoDuiker/QGIS_BGT_Import#12]
De vertaling van diakriete tekens in namen van de OpenbareRuimteLabels gaat niet goed.   Deze komen met name in Friesland nogal veel voor.  Heb niet kunnen achterhalen of het mogelijk door een Windows-instelling komt.  Het GML-bronbestand laat in QGIS wel de juiste schrijfwijze zien in bijbehorende databasetabel:

![image](https://user-images.githubusercontent.com/24246044/71595187-f06d1680-2b3a-11ea-80a3-97997b4ccf5a.png)

Bronbestand is bijgevoegd: 
[BGT diakrietstukje.zip](https://github.com/MarcoDuiker/QGIS_BGT_Import/files/4010649/BGT.diakrietstukje.zip)

**Comment by MarcoDuiker** [comment]
Hans,

Wat je laat zien is vreemd:

- In de attribuuttabel staat het goed
- bij identify wordt het verkeerd getoond
- als label wordt het ook verkeerd getoond

Als alleen de laatste aan de hand was, dan zou ik vermoeden dat ik misschien iets verkeerd heb gedaan met het labelen. De tweede doet me vermoeden dat er iets misgaat in QGIS. Een identify zou in mijn beleving altijd hetzelfde moeten laten zien als de tabel.

Als ik in Linux ga kijken, dan gaat een en ander wel goed:
![Selection_481](https://user-images.githubusercontent.com/28801402/71620513-aa5f9380-2bca-11ea-81ea-5799fd01a4d7.png)
![Selection_483](https://user-images.githubusercontent.com/28801402/71620527-b0ee0b00-2bca-11ea-9d77-95c5ffb77e25.png)
![Selection_482](https://user-images.githubusercontent.com/28801402/71620532-b3e8fb80-2bca-11ea-8663-070dcf4ec9c2.png)

Ik ga er vooralsnog van uit dat het hier geen issue van de plugin betreft, maar een QGIS issue. Wel de moeite waard om te onderzoeken. Daar ga ik nog even mee aan de slag.

**Comment by MarcoDuiker** [comment]
hmm, als ik in windows ga kijken gaat het bij mij ook goed:

![Selection_484](https://user-images.githubusercontent.com/28801402/71621130-d9c3cf80-2bcd-11ea-9f81-40e6fab91b94.png)

Wat mij betreft is het hiermee definitief geen BGT Import plugin issue. Ik sluit daarom dit issue, maar de discussie kan wel gewoon doorlopen.

Misschien is het wel een QGIS issue, maar dan een specifieke versie. Is er wellicht wat aan de hand met je instellingen?
