### ISSUE TITLE
Nieuwe service URL's?

### ISSUE THREAD

**Issue by rduivenvoorde** [MarcoDuiker/QGIS_BGT_Import#14]
Hoi Marco, op het Geoforum vraagt Jeroen of wij in onze plugins wel de nieuwe BGT api url's gebruiken omdat de oude niet meer gaan werken na 1 oktober. Zie verder:

https://geoforum.nl/t/bgt-downloads-in-qgis-plugin/4839

Ik denk idd niet dat jij de boel hebt geupdate toch (althans kijkende naar commits in master :-) )

**Comment by MarcoDuiker** [comment]
De nieuwe API is totaal anders dan de oude en vraagt om een geheel nieuwe implementatie. Al gauw enkele dagen werk.

Wanneer ik in de gelegenheid ben zal ik een nieuwe versie uitbrengen waarin het downloaden disabled is.

**Comment by MarcoDuiker** [comment]
Fixed in 3.20
