### ISSUE TITLE
Download options greyed out

### ISSUE THREAD

**Issue by meesterp** [MarcoDuiker/QGIS_BGT_Import#18]
Wanneer ik de plugin open kan ik op het tabblad 'Complet Package' de radio-buttons 'Download BGT...' en de dropdown die er onder staan niet selecteren.

![image](https://user-images.githubusercontent.com/3451729/166136579-c6b9a132-75e8-473b-bcde-91ab1584d4c0.png)

**Comment by MarcoDuiker** [comment]
Zie https://github.com/MarcoDuiker/QGIS_BGT_Import/issues/14

**Comment by MarcoDuiker** [comment]
Fixed in 3.20
