### ISSUE TITLE
Folder choice

### ISSUE THREAD

**Issue by AllroadsNL** [MarcoDuiker/QGIS_BGT_Import#2]
I open a gml file, to a new project in Qgis.
Because the BGT data are more files, I want to open the next one.
Then it start again in the folder QGIS/bin, as the first time.
I expected to start in the last used folder. It is not annoying.

Is this a plugin problem or a QGIS thing.

**Comment by MarcoDuiker** [comment]
The plugin is only used once per gml to create the import definition file (.gfs) which QGIS uses to import the gml.

I agree it would be nice if plugin and/or QGIS returns to the last used folder. In practice it does happen too often that one ends up in a different folder. 

The easy work around is to select multiple files in the file selection box by holding down shift or ctrl button.

**Comment by AllroadsNL** [comment]
Ofcourse I read it earlier, late, thanks for your explanation.
