### ISSUE TITLE
load time?

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [MarcoDuiker/QGIS_BGT_Import#21]
Hoi Marco,

niet echt een issue, maar wellicht iets om een biertje mee te verdienen :)
Bij mijn installatie (windows10, QGIS 3.28) heeft de BGT Import Plugin een relatief lange load time, gemeten met de Plugin Load Times plugin. Hij geeft bij mij rond de 0,7 seconden aan en staat daarmee steeds in de top 3 langst ladende plugins. Alleen de core plugins processing en saga gis provider duren vaak nog langer.

Ik heb dit  getest in QGIS 3.22, 3.28, 3.30 en 3.32
Ik heb geen idee wat überhaupt van invloed is op een Plugin laad tijd, maar wellicht kun je ergens iets vinden waardoor het sneller gaat? Ik heb de maker van de Plugin Load Times plugin zojuist ook gevraagd of hij ideeën heeft welke factoren de load time beinvloeden.

**Comment by MarcoDuiker** [comment]
Ik ga ervan uit dat dit komt door het initialiseren van de networkmanager.

Aangezien de downloadfunctionaliteit uitgeschakeld is, zou die er wel uitkunnen. 

Je zou het eens kunnen uitproberen door regel 120 in bgt_import.py te wijzigen van

```
self.nam = networkaccessmanager.NetworkAccessManager()
```

in

```
self.nam = None
```

Graag hoor ik og het helpt.

**Comment by Jeroen-GroeneBij** [comment]
Helaas, ik zie nog geen duidelijk verschil. Na een aantal keer opnieuw QGIS starten blijft ie rond de 0,7 seconden staan.

Opvallend is ook dat als ik QGIS de eerste keer start, na opnieuw opstarten windows, alle load times nog veel hoger zijn. Blijkbaar blijft er iets achter in het geheugen van windows om QGIS sneller opnieuw te starten nadat je QGIS afsluit.

**Comment by MarcoDuiker** [comment]
Hmm, dan is het me niet zomaar duidelijk.

Overigens vind ik 0.7 sec niet echt iets om me druk over te gaan maken. 
Als je er last van hebt, dan vink je 'm uit, en als je 'm dan nodig hebt, dan vink je 'm weer aan.

Ik denk dat dat ongeveer 14 seconden duurt. Dus als je 'm vaker dan pak 'm beet 1x per 20x opstarten gebruikt, dan kun je die tijdsinvestering beter achterwege laten.

**Comment by MarcoDuiker** [comment]
Won't fix.
