### ISSUE TITLE
Deel van de GML's wordt geïmporteerd als tabel zonder geometrie

### ISSUE THREAD

**Issue by wvdbee** [MarcoDuiker/QGIS_BGT_Import#22]
QGIS 3.36, GDAL 3.9.0, BGT Import 3.18

Deel van de GML's wordt geconverteerd naar gpkg als tabel zonder geometrie.

Conversie voltooit zonder foutmeldingen: alle GML's worden geïmporteerd in gpkg.
![afbeelding](https://github.com/MarcoDuiker/QGIS_BGT_Import/assets/7975556/af351570-13de-47ed-ae29-546e2912423e)

Na het conversiedeel crasht QGIS. Vermoedelijk doordat het laden van GPKG-layers en het toepassen van QML-stylings meteen fout gaat. 

Handmatig de layers toevoegen aan QGIS:
![afbeelding](https://github.com/MarcoDuiker/QGIS_BGT_Import/assets/7975556/e72b5724-c737-4003-b823-bc7b6b29a370)

![afbeelding](https://github.com/MarcoDuiker/QGIS_BGT_Import/assets/7975556/7488d1e0-707f-42f0-b4c4-4ebde07d8941)

Strack trace van de crash

> Python Stack Trace
> Windows fatal exception: access violation
> 
> Current thread 0x00002068 (most recent call first):
>   
> 
> Thread 0x000044e8 (most recent call first):
>   
> 
> 
> Stack Trace
> 
> 
> RtlpWaitOnCriticalSection :
> RtlpEnterCriticalSectionContended :
> RtlEnterCriticalSection :
> xmlDictFree :
> PyGen_Finalize :
> PyThreadState_Clear :
> PyGILState_Release :
> PyInit_sip :
> pdal::StreamPointTable::reset :
> QgsPresetSchemeColorRamp::clone :
> QgsTask::start :
> QThreadPoolPrivate::reset :
> QThread::start :
> BaseThreadInitThunk :
> RtlUserThreadStart :
> 
> 
> 
> 
> QGIS Info
> QGIS Version: 3.36.3-Maidenhead
> QGIS code revision: 2df96554
> Compiled against Qt: 5.15.13
> Running against Qt: 5.15.13
> Compiled against GDAL: 3.9.0
> Running against GDAL: 3.9.0
> 
> 
> 
> System Info
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 10.0.22631
>

**Comment by wvdbee** [comment]
BGT-extract van vandaag, gebruikt bij deze importtest.

[extract.zip](https://github.com/user-attachments/files/15786108/extract.zip)

**Comment by MarcoDuiker** [comment]
Dit lijkt windows specifiek. Deze extract.zip importeert bij mij zonder problemen.

Zou het kunnen zijn dat je de omgevingsvariabelen PYTHONHOME en/ of PYTHONPATH hebt ingesteld?

Zo ja, dan zou uitzetten moeten helpen. Dat kan middels:

set PYTHONPATH= 
set PYTHONHOME=

**Comment by wvdbee** [comment]
Regulier zijn deze variabelen binnen mijn windows-installatie niet ingesteld.


Deze variabelen worden voor apps, die via OSGeo4W zijn geïnstalleerd, scriptmatig ingesteld wanneer je één van de apps, zoals QGIS, opstart. 
Betekent effectief dan binnen QGIS dit de ingestelde waarden voor de variabelen zijn; opgevraagd via de python-console.

```
import os
print(os.environ['PYTHONHOME'])
print(os.environ['PYTHONPATH'])
```
_C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\grass\grass83\etc\python;_

En effectief is dit het search path van python vanuit QGIS, ook vanaf de QGIS-python-console geraadpleegd:
```
import sys
print(sys.path)

```
_['C:\\Users/Wim/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\geo_sim_processing',
 'C:/OSGeo4W/apps/qgis/./python',
 'C:/Users/Wim/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python',
 'C:/Users/Wim/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins',
 'C:/OSGeo4W/apps/qgis/./python/plugins',
 'C:\\OSGeo4W\\apps\\grass\\grass83\\etc\\python',
 'C:\\OSGeo4W\\bin',
 'C:\\OSGeo4W\\bin\\python312.zip',
 'C:\\OSGeo4W\\apps\\Python312\\DLLs',
 'C:\\OSGeo4W\\apps\\Python312\\Lib',
 'C:\\OSGeo4W\\apps\\Python312',
 'C:\\OSGeo4W\\apps\\Python312\\Lib\\site-packages',
 'C:\\OSGeo4W\\apps\\Python312\\Lib\\site-packages\\win32',
 'C:\\OSGeo4W\\apps\\Python312\\Lib\\site-packages\\win32\\lib',
 'C:\\OSGeo4W\\apps\\Python312\\Lib\\site-packages\\Pythonwin',
 'C:/Users/Wim/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python',
 'C:\\Users\\Wim\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\mmqgis/forms',
 'C:\\Users/Wim/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\qgis_resource_sharing',
 'C:\\Users\\Wim\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\qgis_resource_sharing',
 'C:\\Users\\Wim\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\qgis_resource_sharing\\ext_libs',
 'C:/Werkplekken/Wim/Tijdelijk/BGT/adam03']_

**Comment by wvdbee** [comment]
Nog eens getest met een ander extract.zip, degene die ik vorig jaar bij een ander issue hier op bugnet had geplaatst:

[Deze extract.zip](https://github.com/MarcoDuiker/QGIS_BGT_Import/issues/19#issuecomment-1578233480)

Dat issue was vorig jaar door jou verholpen. Ik kon die extract.zip daarna netjes door de BGT-importer trekken.
Nu nogmaals met de huidige setup loop ik tegen dezelfde fout aan:

- Deel van de GML's worden als nogeometry geïmporteerd.
- Crash na het conversiedeel van de BGT-importer.

**Comment by MarcoDuiker** [comment]
Kun jij de laatste gdal/ ogr versie aangeven waarbij importeren nog goed ging?

**Comment by MarcoDuiker** [comment]
Kun je ook nog voor me proberen of het gebruik van het 2e tabblad wel werkt?

**Comment by wvdbee** [comment]
Tweede tabblad werkt. -ish. Hij heeft wel moeite om bijvoorbeeld de juiste kruinlijngeometrieën eruit te halen. Maar bgt_bak.gml is geen enkel probleem.

**Comment by wvdbee** [comment]
Laatste werkende versie:

QGIS op mijn werkdesktop opgestart. 
QGIS 3.36.6
GDAL 3.8.5

Paar tests gedaan:

1. Twee extracts die ik in dit issue aanhaal: beiden converteren naar geometrieën en niet deelt naar geometrieloze tabellen. QGIS crasht wel op het moment van inladen van de kaartlagen.

2. Extract.zip dat ik april 2024 probleemloos had geconverteerd op, ik vermoed 3.32, met een GDAL die rond die tijd van QGIS courant was. Die converteerde probleemloos én de kaartlagen werden probleemloos met styling in QGIS geladen. Bijbehorend styling-bestand werd ook weggeschreven. 
Op versie 3.36.6 met GDAL 3.8.5 ging de conversie probleemloos. Alle GML's in de extract.zip converteerde zoals verwacht met een resultaat als in april 2024.
Het inladen van kaartlagen stokte bij één van de kaartlagen. Stack trace kon ik niet copypasten; QGIS was compleet bevroren.

Het lijkt dus een dubbel issue:

- Compatibility met GDAL 3.9.0.
- Inladen kaartlagen en toepassen van styling.

**Comment by wvdbee** [comment]
![afbeelding](https://github.com/MarcoDuiker/QGIS_BGT_Import/assets/7975556/feef3067-b9db-4373-b546-b78e0c5eb61f)

Screen van de crash met de deels ingeladen set aan kaartlagen. Beetje info vanuit de stack trace.
