### ISSUE TITLE
BGT Import Qgis crasht bij versie 3.20

### ISSUE THREAD

**Issue by Ruimteloket** [MarcoDuiker/QGIS_BGT_Import#24]
[temp.zip](https://github.com/user-attachments/files/17630434/temp.zip)
[report.docx](https://github.com/user-attachments/files/17630436/report.docx)

**Comment by MarcoDuiker** [comment]
Op mijn systeem gaat dit probleemloos.

- Ubuntu 24.04

```
QGIS-versie | 3.34.4-Prizren | QGIS codebranch | Release 3.34
-- | -- | -- | --
Qt versie | 5.15.13
Python versie | 3.12.2
GDAL/OGR versie | 3.8.4
PROJ versie | 9.4.0
EPSG-register databaseversie | v11.004 (2024-02-24)
GEOS versie | 3.12.1-CAPI-1.18.1
SQLite versie | 3.45.1
PostgreSQL client versie | 16.2 (Ubuntu 16.2-1ubuntu3)
SpatiaLite versie | 5.1.0
QWT versie | 6.1.4
QScintilla2 versie | 2.14.1
OS versie | Ubuntu 24.04.1 LTS
  |   |   |  
Actieve Python plug-ins
BGTImport | 3.20
pdokservicesplugin | 5.1.1
plugin_reloader | 0.17
gio_import | 0.9.1
QuickPrint | 3.6.1
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6


```

Zou het een windows dingetje zijn?

**Comment by Ruimteloket** [comment]
Hoi Marco,

Toch iets met qgis versie 3.24.12 op mijn systeem. Met versie 3.28 gaat het wel goed. Dank voor de hulp.

Met vriendelijke groeten,
Martijn van Bodegraven

___________________________________________________
Martijn van Bodegraven | Ruimteloket B.V. |
| Tel 085-0163874 | Mob. 06 26789283 |

Vrijdagochtend afwezig

***@***.*** / www.ruimteloket.nl<http://www.ruimteloket.nl/>

Ruimteloket, data in kaart
____________________________________________________
***@***.***

Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ruimteloket B.V. accepteert geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ruimteloket B.V. does not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

Van: Marco Duiker ***@***.***>
Verzonden: dinsdag 5 november 2024 13:18
Aan: MarcoDuiker/QGIS_BGT_Import ***@***.***>
CC: Martijn van Bodegraven ***@***.***>; Author ***@***.***>
Onderwerp: Re: [MarcoDuiker/QGIS_BGT_Import] BGT Import Qgis crasht bij versie 3.20 (Issue #24)


Op mijn systeem gaat dit probleemloos.

  *   Ubuntu 24.04

QGIS-versie | 3.34.4-Prizren | QGIS codebranch | Release 3.34

-- | -- | -- | --

Qt versie | 5.15.13

Python versie | 3.12.2

GDAL/OGR versie | 3.8.4

PROJ versie | 9.4.0

EPSG-register databaseversie | v11.004 (2024-02-24)

GEOS versie | 3.12.1-CAPI-1.18.1

SQLite versie | 3.45.1

PostgreSQL client versie | 16.2 (Ubuntu 16.2-1ubuntu3)

SpatiaLite versie | 5.1.0

QWT versie | 6.1.4

QScintilla2 versie | 2.14.1

OS versie | Ubuntu 24.04.1 LTS

  |   |   |

Actieve Python plug-ins

BGTImport | 3.20

pdokservicesplugin | 5.1.1

plugin_reloader | 0.17

gio_import | 0.9.1

QuickPrint | 3.6.1

grassprovider | 2.12.99

db_manager | 0.1.20

processing | 2.12.99

MetaSearch | 0.3.6





Zou het een windows dingetje zijn?

**Comment by MarcoDuiker** [comment]
Fijn dat ie het doet. Z
